### ISSUE TITLE
Help Please!

### ISSUE THREAD

**Issue by Ice64** [ConnorLinfoot/CratesPlus#19] opened 2015-08-07 05:43 UTC
![2015-08-07_00 51 21](https://cloud.githubusercontent.com/assets/8510014/9129524/7abf7994-3c9e-11e5-86a7-428f8d49834f.png)
For some reason the grates glitch and I can`t delete any of the crate I placed down. Like when I place the crate down, it glitches for a split second and then all that there is is the hologram that is suppose to be above the crate. Now it just floats there and I can`t remove it. I tried removing the plugin and restarting my server but it still floats there. I don`t know what to do so please help asap!

**Comment by ConnorLinfoot** [comment] 2015-08-07 08:48
Duplicate of issue #16

**Closed by ConnorLinfoot** 2015-08-07 08:48 UTC
