### ISSUE TITLE
Crate Example is not going away

### ISSUE THREAD

**Issue by StaticCraft** [ConnorLinfoot/CratesPlus#21] opened 2015-08-11 19:25 UTC
Hello, 
I have factions installed and when i placed the crate down it only showed the title of the crate not the crate, I think this was because i didnt have /.f admin enabled so i enabled /f admin, and it will not allow me to remove the title i removed the plugin and still had the same problem could you respond asap

Thanks
Steven

**Comment by ConnorLinfoot** [comment] 2015-08-13 09:51
Duplicate of issue #16

**Closed by ConnorLinfoot** 2015-08-13 09:51 UTC

**Comment by StaticCraft** [comment] 2015-08-13 22:20
Thanks so much i tried to get ride of it with creeper eggs hahaha

**Comment by StaticCraft** [comment] 2015-08-13 22:20
you sould really consider putting that in the desc of the chest plus plugin
