### ISSUE TITLE
Settings GUI Game Crash

### ISSUE THREAD

**Issue by RexTheMon** [ConnorLinfoot/CratesPlus#590] opened 2018-11-05 20:14 UTC
### Versions:
CratesPlus version - latest.
Spigot version - 1.13.2
Client version - 1.13.2

### Errors:
Client crash log - https://hastebin.com/bisozabaxa.js
Client disconnection message in console - https://hastebin.com/xavayugima.nginx

### Actions to reproduce (if known):
Run the command /crate settings
Click Edit Crates
Click your Crate
Click rename Crate+

**Comment by ConnorLinfoot** [comment] 2018-11-05 22:14
Duplicate of #576

**Closed by ConnorLinfoot** 2018-11-05 22:14 UTC
