### ISSUE TITLE
Can CratesPlus prevent a player from getting the same item twice when using one specific crate?

### ISSUE THREAD

**Issue by Banjie565** [ConnorLinfoot/CratesPlus#556] opened 2018-06-11 00:33 UTC
Hello all,

I have a specific question. I have a crate on my server called the permissions crate that gives out permissions. I want to make it so the same player does not get the same permission twice when using the permission crate. For example, let's say Bob get a permission key and uses it on the permission crate and gets the ability to fly, then the following week, Bob get another permission key and uses it once again on the permission crate and gets fly once again. Is there any way to prevent this from happening? Thank you for your help!

**Comment by ConnorLinfoot** [comment] 2018-09-16 21:46
This is a feature planned for v5. Unfortunately, I don't yet have an ETA for v5. Closing as this is a duplicate of #255

**Closed by ConnorLinfoot** 2018-09-16 21:46 UTC
