### ISSUE TITLE
Crate will not open if not opped! Please help!

### ISSUE THREAD

**Issue by HeroKG** [ConnorLinfoot/CratesPlus#243] opened 2016-06-21 23:19 UTC
###Problem
Whenever a non op player tries to open a crate using a key the crate does not open. Is there any permissions the player needs to open the crate? Also, the crate doesn't give any messages when it does not open. Left clicking still opens reward GUI.

### Link/paste of stack trace (if any)
/Cratesplus debug did not work. It said "Unkown arg" when I tried to enter it.

### Plugin list:
CratesPlus, Coreprotect, Worldedit, Essentials, GroupManager, ClearLag, PlugMan, Votifier, ActionBarAPI, Holograms, WorldGuard, KitAdder, TitleAPI, Obsidianbreaker, EssentialsChat, McMMO, Vault, EssentialsSpawn, PvPManager, EnjinMinecraftPlugin, PickupSpawners, Citizens, Playervaults, Kingdoms, Factionmobs

### Actions to reproduce (if known):
Trying to open a crate if not op.

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
http://pastebin.com/vAFGL8Qu

### CratesPlus data.yml
http://pastebin.com/3taNMqT6

**Comment by ConnorLinfoot** [comment] 2016-06-22 08:04
Duplicate of #228, issue caused by mis-configuration of other plugins or your server.

**Closed by ConnorLinfoot** 2016-06-22 08:04 UTC
