### ISSUE TITLE
limited Items

### ISSUE THREAD

**Issue by miremo** [ConnorLinfoot/CratesPlus#139] opened 2016-03-15 01:14 UTC
Hello,

I have a huge issue with these crates and I am not certain if it is part of the plugin or not. Whenever I try to add over 6 items the seventh item will not appear... please help.

**Comment by miremo** [comment] 2016-03-15 04:15
I am running the latest version

**Comment by CaptDarkStar** [comment] 2016-03-15 05:51
Latest recommended version, or the latest developmental build? Can you post your config via pastebin.com? How are you adding the items to the crates? Are you using percentages, and if so, do they add up to exactly 100%? We need these details in order to help further. 

However, to answer your issue with only the information you provided currently, it would have to be an error with another plugin or a mistake in your config. I have 11+ items in my chests with no issues.

**Comment by ConnorLinfoot** [comment] 2016-03-15 15:00
As said above this is usually caused by a configuration error. Will close this issue but you can still reply with your config if you need help.

**Closed by ConnorLinfoot** 2016-03-15 15:00 UTC

**Comment by miremo** [comment] 2016-03-15 15:46
So it will stop letting me add items as soon as the percentage adds up to 100%?

**Comment by miremo** [comment] 2016-03-15 15:46
I will post my config if that is not the case
