### ISSUE TITLE
Snapshot 16 hologram disappearing

### ISSUE THREAD

**Issue by Sikatsu** [ConnorLinfoot/CratesPlus#136] opened 2016-03-13 20:04 UTC
On snapshot 16, the hologram is bugged. It keeps dissapearing. (http://prntscr.com/aeu71p)

The chest still works fine.

**Comment by ConnorLinfoot** [comment] 2016-03-13 22:21
Try snapshot 17 and see if it's any better

**Comment by Sikatsu** [comment] 2016-03-13 22:39
That will be tomorrow, heading to bed already. Thanks for the update :)

**Comment by CaptDarkStar** [comment] 2016-03-14 04:07
I can still confirm this is occurring in snapshot 17. No errors in console or anything. I watched them flicker for a moment and then disappear.

**Comment by ConnorLinfoot** [comment] 2016-03-14 07:48
Are you running any other plugins? And what version of spigot are you using?

The new snapshots are now using packets instead of actual holograms. I would hope it would have no issues but apparently not.

**Comment by Sikatsu** [comment] 2016-03-14 08:10
Same here. The hologram still vanishing. I'm 1 version behind on spigot, need my plugin list?

**Comment by ConnorLinfoot** [comment] 2016-03-14 08:23
I'm not having any issues, if you could send your plugin list that'd be great. Are you using Spigot 1.9?

**Comment by Sikatsu** [comment] 2016-03-14 08:30
I just reloaded the plugin and the hologram is back now, probably will vanish again maybe (will let you know)

List: http://prntscr.com/af0u15
Spigot: 1.9 1 version behind.

**Comment by ConnorLinfoot** [comment] 2016-03-14 08:33
I imagine the issue is that when you join it's sending the packets to fast before you're even fully connected. So they'll probably go away if you re-log but I'll see what I can do.

**Comment by ConnorLinfoot** [comment] 2016-03-14 08:53
Not sure if the latest snapshot will improve this at all, I've increased the delay on login so see how that goes. I'm guessing it depends on ping? But I've used the same delay HoloAPI is using now.

**Comment by CaptDarkStar** [comment] 2016-03-14 09:27
This issue is still present in Snapshot 18 that I just tested. Was working perfectly in 15. What was changed between snapshot 15 and 16?

**Comment by ConnorLinfoot** [comment] 2016-03-14 11:46
They're now using packets in 16+ to fix issues with entity clear and world guard sometimes breaking it. Will do more testing on them later as it just seems the player login packets are being sent to quickly.

**Comment by CaptDarkStar** [comment] 2016-03-14 17:50
I am not sure if this is because I didnt restart after the new upload, or because of something else, but I seem to longer be having this issue at the moment. I will test a little further, but I think it is fine now.

**Comment by Sikatsu** [comment] 2016-03-14 20:37
Me neither on snapshot 18 :)

**Comment by ConnorLinfoot** [comment] 2016-03-15 15:00
Will close this issue then, if anyone has any problems again let me know :)

**Closed by ConnorLinfoot** 2016-03-15 15:00 UTC

**Comment by Pspman345** [comment] 2017-04-18 23:31
Still having the issue on v4.4. I'm using Holo Displays v2.2.5 as well.
