### ISSUE TITLE
remove crate on use

### ISSUE THREAD

**Issue by TheSaltyPug** [ConnorLinfoot/CratesPlus#259] opened 2016-07-06 18:41 UTC
Is there a way to make it so that when a player places down a crate and uses a key on it, immediately afterwards the crate disappears and cannot be used again? 
Or can you make it just in a GUI/ So you dont have to put the crate down and just have to have a key or something?

**Comment by ConnorLinfoot** [comment] 2016-07-06 20:04
The idea of different crate types will be added at a later date. Duplicate of #204

**Closed by ConnorLinfoot** 2016-07-06 20:04 UTC
