### ISSUE TITLE
In-game editor broken.

### ISSUE THREAD

**Issue by Sikatsu** [ConnorLinfoot/CratesPlus#131] opened 2016-03-11 22:29 UTC
When I want to click on ''Edit winnings'' it gives me this error:

`11.03 23:25:58 [Server] ERROR Could not pass event InventoryClickEvent to CratesPlus v4.0.0-SNAPSHOT-15
11.03 23:25:58 [Server] INFO org.bukkit.event.EventException
11.03 23:25:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1844) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
11.03 23:25:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:58 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
11.03 23:25:58 [Server] INFO Caused by: java.lang.NullPointerException
11.03 23:25:59 [Server] ERROR Could not pass event InventoryClickEvent to CratesPlus v4.0.0-SNAPSHOT-15
11.03 23:25:59 [Server] INFO org.bukkit.event.EventException
11.03 23:25:59 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:59 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:59 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1844) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:59 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:59 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:59 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9-R0.1.jar:git-Spigot-b1c1b55-7d330bc]
11.03 23:25:59 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]`

**Comment by CaptDarkStar** [comment] 2016-03-12 02:05
This seems to be an issue with your config file. I have zero issues in game with mine, but when I use your config file, I also get this error. I might recommend starting with a fresh config file and use the in game editor to add ALL the items first before adding percentages and such first.

**Comment by Sikatsu** [comment] 2016-03-12 09:25
I used the in-game editor, I'm confused.

**Comment by Sikatsu** [comment] 2016-03-12 11:38
Tried, no succes, config: http://pastebin.com/zWvUQgkv

**Comment by CaptDarkStar** [comment] 2016-03-12 13:26
@ConnorLinfoot - Any chance we can merge this issue with issue #130 ? They are both under the same problem from what I can tell. It is enchantment related based on my testing. Also, could this possibly be a conversion issue using the GUI in-game?

@Sikatsu - This error, and the other error you are experience is related to your enchantments that you have configured. Upon some quick testing, I found the "MENDING-1" enchantment on item 3 (gold chestplate) was causing a problem. I suggest going though and checking all your enchant options one by one to make sure they are valid enchantments and are allowed on the item. (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html)

**Comment by Sikatsu** [comment] 2016-03-12 17:52
@CaptDarkStar There should be nothing wrong with mending actually, even while I remove it the error still exists. The enchants are all set within the game, so I don't get what's wrong with the enchants.

I can't find any issue at all within the config, besides that it worked on an earlier snapshot without issues..

**Comment by Sikatsu** [comment] 2016-03-12 18:19
If I remove all the enchants from these items: http://prntscr.com/aee36r
It works. If I give any of the items one enchant, doesn't matter which, it breaks again? wtf.

**Comment by Sikatsu** [comment] 2016-03-12 18:21
The enchant system in the config must be broken, if only one item with an enchant is within a crate, the ingame editor breaks. @ConnorLinfoot @CaptDarkStar

**Comment by CaptDarkStar** [comment] 2016-03-13 02:10
I had no issues adding basic enchantments with any of your items. As I said, the MENDING-1 was an example of the first issue I ran into. This was just me testing item by item with your config and that was the first thing I ran into. I don't have time right now to sit for a couple hours and test every possibility and attempt to write a new config for you. If I have time later, I can do some work on it. However I also do not know what version MC you are using for this either, which could also be part of the problem.

**Comment by Sikatsu** [comment] 2016-03-13 08:18
If I remove mending, it still breaks. Lets say, I remove all enchants and give an axe durability, it breaks. It doesn't matter which enchant and which item, if I use even one enchant it just breaks. I tested yesterday for an hour but the only solution is removing all enchants.

I'm using snapshot 15 and i'm 2 versions behind on Spigot.

**Comment by ConnorLinfoot** [comment] 2016-03-13 12:17
Sorry I haven't looked into these issues yet, had a chilled out day yesterday. Will look into it today and hopefully see what the issue is or fix it.

**Comment by Sikatsu** [comment] 2016-03-13 12:37
Thanks Connor! Appreciate it :)

**Comment by ConnorLinfoot** [comment] 2016-03-13 12:56
Found the issue, it's me being an idiot and removing support for levels "DURABILITY-1" (-1 part being broken!)

Will be fixed in the next snapshot!

**Comment by ConnorLinfoot** [comment] 2016-03-13 13:36
Alright, try snapshot 16 and let me know if you still have any issues.

**Closed by ConnorLinfoot** 2016-03-13 13:36 UTC

**Comment by Sikatsu** [comment] 2016-03-13 14:07
Works, thanks for fixing!
