### ISSUE TITLE
Crate opening sounds are too loud

### ISSUE THREAD

**Issue by MithrandirCraft** [ConnorLinfoot/CratesPlus#233] opened 2016-06-15 22:42 UTC
**Please use one of the issue templates below. Issues not using the templates will likely be closed!**

# Configuration issue

### Link/paste of stack trace

None

### Plugin list:
No need

### Actions to reproduce (if known):
Just create a chest and use it.

### Bukkit/Spigot Version:
Spigot for MC 1.9.4

### CratesPlus Version:
4.1.0
+
CSGO 1.0

### CratesPlus config.yml
http://hastebin.com/vehemufoke.vhdl

### CratesPlus data.yml
http://hastebin.com/ipebogobeh.1c

# Suggestion

Crate opening sounds are too loud. There needs to be an option in order to control the volume for them, and maybe even customize. The sound is so loud it can be heard from a distance of 100 blocks, which I personally find excessive.

**Comment by ConnorLinfoot** [comment] 2016-06-15 22:44
Duplicate of #229

**Closed by ConnorLinfoot** 2016-06-15 22:44 UTC
