### ISSUE TITLE
ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutOpenSignEditor

### ISSUE THREAD

**Issue by Eufranio** [ConnorLinfoot/CratesPlus#342] opened 2017-01-17 01:24 UTC
Hello, first of all I want to thank you for developing this amazing Crates plugin. Recently I added it to my 1.7.10 (Thermos, build 58, Forge 1614) server. The plugin works well, but I can't create a crate with the **/crate create** command. It will throw this error at the console:
```
[02:19:30 INFO]: PotterCraft_ issued server command: /crate create
[02:19:30 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutOpenSignEditor
[02:19:30 WARN]:        at java.lang.Class.forName0(Native Method)
[02:19:30 WARN]:        at java.lang.Class.forName(Class.java:264)
[02:19:30 WARN]:        at plus.crates.Utils.ReflectionUtil.getClass(ReflectionUtil.java:30)
[02:19:30 WARN]:        at plus.crates.Utils.ReflectionUtil.getNMSClass(ReflectionUtil.java:38)
[02:19:30 WARN]:        at plus.crates.Commands.CrateCommand.onCommand(CrateCommand.java:199)
[02:19:30 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[02:19:30 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[02:19:30 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740)
[02:19:30 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370)
[02:19:30 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107)
[02:19:30 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[02:19:30 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[02:19:30 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[02:19:30 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[02:19:30 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[02:19:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[02:19:30 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[02:19:30 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[02:19:30 WARN]:        at java.lang.Thread.run(Thread.java:745)
[02:19:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'crate' in plugin CratesPlus v4.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
```
I don't have much to offer here, since I didn't change anything in the config. As stated above, I'm running Thermos (a bukkit-forge server software) build 58, and forge 1614 for 1.7.10. I have also ProtocolLib in my server, the 1.7 version.
I ran **/crates debug** and the output is this link: https://mcdebug.xyz/cratesplus/4494

Thanks.

**Comment by ConnorLinfoot** [comment] 2017-01-18 10:50
Duplicate of #293

**Closed** 2017-01-18 10:50 UTC
Labels: 1.7, bug, duplicate
