### ISSUE TITLE
Holograms Not Disapearing

### ISSUE THREAD

**Issue by Shane1928** [ConnorLinfoot/CratesPlus#43] opened 2015-10-25 18:45 UTC
Hello, for some reason when I tried destroying a crate the hologram did not disappear a long with it and I would like to know how to fix this issue, thank you.

**Comment by Shane1928** [comment] 2015-10-25 20:04
I fixed the issue, just type:
/entitydata @e[type=ArmorStand,r3] {Invisible:0}

**Comment by ConnorLinfoot** [comment] 2015-10-26 08:37
Duplicate of issue #16 (Resolved anyway)

**Closed by ConnorLinfoot** 2015-10-26 08:37 UTC
