### ISSUE TITLE
Question: Custom items in crates.

### ISSUE THREAD

**Issue by Corcustos** [ConnorLinfoot/CratesPlus#352] opened 2017-02-22 23:56 UTC
This is a question, rather an an error. Although, if what I'm asking is not possible, then it could possibly be considered as an issue or bug. I didn't think it was needed to use the template due to the fact that there is no error log, and pasting the entire config would be irrelevant because it's just one section of it.

What I'm trying to do is put custom items such as potions with custom effects using the /potion essentials command, the heads of specific usernames, colored leather armor, and custom MythicDrops items. However, when I use /crate settings to edit the winnings of the crates, the crates revert my potions into vanilla potions, defaults the heads to a steve head, removes the color of the leather armor, and the MythicDrop items don't work properly. The /crate settings command does not save custom items properly, so I figured I'll just go into the config and change this myself. However, I'm not exactly sure what to put under the "Item Data" to make this happen, or if it's even done there.

Example:
        Type: ITEM
        Item Type: SKULL_ITEM
        Item Data: 3 
        Name: '&r&bChicken Head'
        Amount: 1
        Enchantments: []
        Lore: []

^ I want that to have the user of "MHF_Chicken", but how would I do this?

Example 2:
        Type: ITEM
        Item Type: POTION
        Item Data: 0
        Name: '&r&dChicken On A Raft'
        Amount: 1
        Enchantments: []
        Lore: []

^ I would like this potion to be a healing potion, but with resistance, blindness, weakness, fatigue, and nausea on it. 

I can create the custom items, but CratesPlus refuses to give them back in the same condition and with the same data as they had when added through /crate settings. That's what I'm trying to find out how to do.

Overall I love CratesPlus and have been using it in my previous servers, but now that I'm making an almost semi-custom server I need custom item support. I really don't want to switch crate plugins either since I'm comfortable with CratesPlus. Hopefully you guys can help me with this, because if not, this will be a large wall in my server progression as I'll have to stick to boring default/normal crate winnings. Any response/help is much appreciated. Thanks.

(P.S. I thought about using commands to give specific items, but that won't work with MythicDrops items or the player heads because I can't specify an item for MD, and the head still won't display in the GUI properly.)

**Comment by ConnorLinfoot** [comment] 2017-03-01 15:45
Duplicate of #235, this is planned hopefully one day...

**Closed by ConnorLinfoot** 2017-03-01 15:45 UTC

**Comment by Corcustos** [comment] 2017-03-05 22:59
So will this be soon, or will I have to switch to a crates plugin capable of doing this?
