### ISSUE TITLE
i

### ISSUE THREAD

**Issue by naplover** [ConnorLinfoot/CratesPlus#311] opened 2016-09-17 16:14 UTC
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you.
### Link/paste of stack trace/error (if any)

```
You can also simply just use code formatting in markdown!
```

**_We need all of the stack trace! Do not cut off parts of it.**_
### Debug Link

https://mcdebug.xyz/cratesplus/8223z
### Actions to reproduce (if known):

My first issue is that whenever i do /crate create it brings up a sign, but after hitting enter on the sign it disconnects me from the server. Also when i do /crate create Example it makes the crate but doesn't give me/tell me how to get the crate itself.

**Comment by Greenfoot5** [comment] 2016-09-18 08:39
/crate crate <player name> <crate> will give you the crate. Player name and crate might be switched around though. I don't know about the sign but you can edit a crate by doing /crate settings.

**Comment by gappleburst** [comment] 2016-09-27 23:25
Ah yes the same thing is happening to me with the sign. When you create a Crate, just don't type /crate create. It's glitchy. do /crate create (name) all in one command.

**Comment by ConnorLinfoot** [comment] 2016-12-11 22:58
The debug link you posted isn't valid, are you on Bukkit 1.7?

**Comment by ConnorLinfoot** [comment] 2017-03-27 08:54
Assuming duplicate of #293, closing.

**Closed by ConnorLinfoot** 2017-03-27 08:54 UTC
Labels: bug
