### ISSUE TITLE
Items being taken from crate preview.

### ISSUE THREAD

**Issue by NothingClassy** [ConnorLinfoot/CratesPlus#40] opened 2015-10-12 19:06 UTC
Hello. I have recently added your plugin to my server and I have found it to be very good. However, there is an issue occurring when players preview the crate content. They are able to take the content from the preview which means they can get unlimited items from the crate. I have ran this plugin alone without any other plugins to see if any conflicts occurred. However, I ran it on its own and the issue still occurred so it is not being caused by another plugin. Can you please fix this as it would make your plugin perfect for my server if there wasn't a glitch to get items from the preview.
(This GYAZO link shows you a screenshot of my plugin list and showing the mob spawner I took from preview https://gyazo.com/82a402297e54433c43aa4ea1d4607d55)
Many thanks, 
NothingClassy.

**Comment by csorrows** [comment] 2015-10-24 11:12
What method are you using to get the items out of the preview? This would help the author replicate the issue.

**Comment by NothingClassy** [comment] 2015-10-27 18:36
I just open the chest which is setup as a crate and it allows me to take the items from preview like taking items from a normal chest. Once I take them and close the chest I keep the items but they then reappear in preview mode, meaning endless supplies of items are available from the crate.

**Comment by sargis123** [comment] 2015-10-29 20:03
Same I need help.

**Comment by ConnorLinfoot** [comment] 2015-10-31 13:02
Can you please specify which version of Spigot you are using? And if any errors show in console.

**Comment by sargis123** [comment] 2015-10-31 17:44
craftbukkit_1.8.8_efd6cb0.jar

**Comment by ConnorLinfoot** [comment] 2015-10-31 17:53
@sargis123 The plugin is NOT supported on Craft Bukkit. Is is built to run with Spigot.

**Comment by ConnorLinfoot** [comment] 2015-11-02 16:19
Assuming issue is caused by not using Spigot with other users also. Closing.

**Closed by ConnorLinfoot** 2015-11-02 16:19 UTC
