### ISSUE TITLE
Client crash!

### ISSUE THREAD

**Issue by mrgeneralq** [ConnorLinfoot/CratesPlus#582] opened 2018-09-23 17:45 UTC
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Info

Due to a change in the GitHub Gist API the debug command currently doesn't work. Please can you upload your `config.yml` and provide your Bukkit version. If possible a plugin list and providing your `data.yml` is also appreciated and may be requested if needed.

### Link/paste of stack trace/error (if any)
> [19:36:22 INFO]: xMiningCreeper lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ClassCastException: net.minecraft.server.v1_13_R2.BlockPosition cannot be cast to [Ljava.lang.String;

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Go the the settings page, then navigate to any crate, click on the icon to rename a crate (crash)

**Comment by ConnorLinfoot** [comment] 2018-09-23 18:11
Duplicate of #576

**Closed by ConnorLinfoot** 2018-09-23 18:11 UTC
Labels: duplicate
