### ISSUE TITLE
Crates startup error

### ISSUE THREAD

**Issue by Xubels** [ConnorLinfoot/CratesPlus#541] opened 2018-04-14 03:23 UTC
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link
___Enter your debug link from `/crates debug`. Not providing this may result in the issue being closed without warning. If you are unable to use this command please provide your Bukkit version, a list of plugins and your config.yml for CratesPlus.___

https://mcdebug.xyz/cratesplus/share/VAmfoiE2p4

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

[23:18:25 ERROR]: Error occurred while enabling CratesPlus v4.4.5 (Is it up to date?)
java.lang.NullPointerException: null
        at org.bukkit.Location.getBlock(Location.java:91) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
        at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

**Comment by ConnorLinfoot** [comment] 2018-05-27 11:26
Duplicate of #534

**Closed by ConnorLinfoot** 2018-05-27 11:26 UTC
Labels: bug, duplicate
