### ISSUE TITLE
Snapshot 20 issue

### ISSUE THREAD

**Issue by Sikatsu** [ConnorLinfoot/CratesPlus#146] opened 2016-03-17 20:24 UTC
My admin just commented about a major bug with the crates. I'm currently not home, but he explained it as this:

"A player, opened the crate and the GUI didn't close. Instead, he recieved all the items he could win and the GUI didn't want to close until closing minecraft"

**Comment by Sikatsu** [comment] 2016-03-17 20:52
It still happens on Snapshot 10, when I open the chest it keeps filling my inventory: http://prntscr.com/agkd19

**Comment by Sikatsu** [comment] 2016-03-17 20:53
Maybe giving the error will be usefull too.

`17.03 21:48:53 [Server] WARN Exception in thread "Craft Scheduler Thread - 2539" 
17.03 21:48:53 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin CratesPlus v4.0.0-SNAPSHOT-21 generated an exception while executing task 6697
17.03 21:48:53 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
17.03 21:48:53 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
17.03 21:48:53 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
17.03 21:48:53 [Server] INFO at java.lang.Thread.run(Thread.java:745)
17.03 21:48:53 [Server] INFO Caused by: java.lang.IllegalStateException: Asynchronous entity add!
17.03 21:48:53 [Server] INFO at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
17.03 21:48:53 [Server] INFO at net.minecraft.server.v1_9_R1.World.addEntity(World.java:940)
17.03 21:48:53 [Server] INFO at net.minecraft.server.v1_9_R1.World.addEntity(World.java:936)
17.03 21:48:53 [Server] INFO at net.minecraft.server.v1_9_R1.WorldServer.addEntity(WorldServer.java:1073)
17.03 21:48:54 [Multicraft] Skipped 350 lines due to rate limit (30/s)`

**Comment by ConnorLinfoot** [comment] 2016-03-17 23:30
Config file? Not able to reproduce.

**Comment by ConnorLinfoot** [comment] 2016-03-17 23:34
This error is because of the firework I believe, try disabling that! Will fix in the next snapshot!

**Comment by ConnorLinfoot** [comment] 2016-03-18 08:42
Try snapshot 22 please, should be fixed.

**Comment by Sikatsu** [comment] 2016-03-18 09:48
Yup, works fine now. Thanks!

**Closed** 2016-03-18 11:04 UTC
