### ISSUE TITLE
Edit Cratescolor

### ISSUE THREAD

**Issue by Sprungente** [ConnorLinfoot/CratesPlus#584] opened 2018-10-06 12:28 UTC
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Info
No Config issue ; 

Due to a change in the GitHub Gist API the debug command currently doesn't work. Please can you upload your `config.yml` and provide your Bukkit version. If possible a plugin list and providing your `data.yml` is also appreciated and may be requested if needed.

### Link/paste of stack trace/error (if any)

No error occoured

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
Clicking in the edit Cratescolormenu on a Item. Nothing will happen 

### Additional Information
Spigot 1.13.1 
Cratesplus 4.5.1

**Comment by ConnorLinfoot** [comment] 2018-10-06 14:36
Duplicate of #576

**Closed by ConnorLinfoot** 2018-10-06 14:36 UTC
