### ISSUE TITLE
Crates are not opening

### ISSUE THREAD

**Issue by d3ath2005** [ConnorLinfoot/CratesPlus#390] opened 2017-04-22 10:18 UTC
**Stack Trace:** 
`21.04 17:57:11 [Server] ERROR Could not pass event PlayerInteractEvent to CratesPlus v4.3.3
21.04 17:57:11 [Server] INFO org.bukkit.event.EventException
21.04 17:57:11 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
21.04 17:57:11 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
21.04 17:57:11 [Server] INFO Caused by: java.lang.NullPointerException
21.04 17:57:11 [Server] INFO at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:77) ~[?:?]
21.04 17:57:11 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
21.04 17:57:11 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
21.04 17:57:11 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
21.04 17:57:11 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
21.04 17:57:11 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 17:57:11 [Server] INFO ... 17 more`
**Debug Link (/crate debug):** 
https://mcdebug.xyz/cratesplus/share/DNJr4q2gxW

**Problem:** 
Whenever I right-click on a crate It opens as a normal chest (If holding key or not).

**Comment by ConnorLinfoot** [comment] 2017-04-22 11:15
Duplicate of #375

**Closed by ConnorLinfoot** 2017-04-22 11:15 UTC
Labels: duplicate
