### ISSUE TITLE
No open

### ISSUE THREAD

**Issue by Ula492** [ConnorLinfoot/CratesPlus#237] opened 2016-06-16 14:41 UTC
My players are not able to open the crates with out OP is their a permission so players can open the crate?

**Comment by ConnorLinfoot** [comment] 2016-06-16 14:43
Duplicate of #228, issue caused by mis-configuration of other plugins.

**Closed by ConnorLinfoot** 2016-06-16 14:43 UTC

**Comment by Ula492** [comment] 2016-06-16 14:49
did not work

**Comment by Ula492** [comment] 2016-06-16 14:49
does not say any worldguard msgs

**Comment by ConnorLinfoot** [comment] 2016-06-16 14:59
It'll be due to another plugin. CratesPlus has no permissions or anything blocking the opening of crates.

**Comment by Ula492** [comment] 2016-06-16 15:06
http://imgur.com/cKB9gG0

**Comment by Ula492** [comment] 2016-06-16 15:24
Help?

**Comment by ConnorLinfoot** [comment] 2016-06-16 15:54
It's not an issue with the plugin. Something isn't configured right with your server.

**Comment by Ula492** [comment] 2016-06-16 16:15
Like what?

**Comment by ConnorLinfoot** [comment] 2016-06-16 16:28
I wouldn't know. I don't use your plugins. Maybe also check your spawn protection.
